"""Fetch the cross-generator evaluation set: FakeMusicCaps + MusicCaps.

This is the unseen-generator test the project's headline claim rests on, set
against the base paper's cross-generator F1 of 0.629.

Both halves have to be sampled rather than downloaded whole -- the Zenodo
release is 12 GB and the MusicCaps audio copy is 8.7 GB, against ~15 GB of free
disk. FakeMusicCaps is streamed out of its zip like the SONICS parts; MusicCaps
is a flat directory of wavs on the Hub, so individual files are pulled.

The two halves come from the same corpus by construction: FakeMusicCaps is
MusicCaps re-generated by five text-to-music models, so the real and generated
clips describe the same music. That is what makes the comparison meaningful --
pairing generated clips with real audio from a different corpus would measure
the domain gap instead.

    python scripts/fetch_cross_generator.py --out ~/sonics/fmc --per-generator 120 --real 500
"""

from __future__ import annotations

import argparse
import time
from pathlib import Path

import requests

FMC_URL = "https://zenodo.org/records/15063698/files/FakeMusicCaps.zip?download=1"
MUSICCAPS_REPO = "kelvincai/MusicCaps_30s_wav"


def stream_fakemusiccaps(out: Path, per_generator: int, retries: int = 10) -> int:
    """Pull up to `per_generator` clips from each model's directory.

    Stops as soon as every generator has its quota, so the rest of the 12 GB
    transfer is abandoned.
    """
    from stream_unzip import stream_unzip

    out.mkdir(parents=True, exist_ok=True)
    start = time.time()

    def counts() -> dict[str, int]:
        return {d.name: len(list(d.glob("*.wav"))) for d in out.iterdir() if d.is_dir()}

    for attempt in range(1, retries + 1):
        have = counts()
        if have and all(v >= per_generator for v in have.values()) and len(have) >= 5:
            break
        try:
            with requests.get(FMC_URL, stream=True, timeout=120) as resp:
                resp.raise_for_status()
                for name, _size, unzipped in stream_unzip(
                        resp.iter_content(chunk_size=262144)):
                    path = Path(name.decode(errors="replace"))
                    # Layout is <root>/<GeneratorName>/<ytid>.wav; the directory
                    # name is the attribution label.
                    if path.suffix.lower() not in (".wav", ".mp3") or len(path.parts) < 2:
                        for _ in unzipped:
                            pass
                        continue
                    generator = path.parts[-2]
                    target_dir = out / generator
                    target = target_dir / path.name
                    n_have = len(list(target_dir.glob("*.wav"))) if target_dir.exists() else 0
                    if target.exists() or n_have >= per_generator:
                        for _ in unzipped:
                            pass
                        continue

                    target_dir.mkdir(parents=True, exist_ok=True)
                    tmp = target.with_suffix(".part")
                    with tmp.open("wb") as fh:
                        for chunk in unzipped:
                            fh.write(chunk)
                    tmp.rename(target)

                    have = counts()
                    total = sum(have.values())
                    if total % 50 == 0:
                        print(f"  fmc {total} clips {have} "
                              f"{time.time() - start:.0f}s", flush=True)
                    if len(have) >= 5 and all(v >= per_generator for v in have.values()):
                        print(f"  fmc quota reached: {have}", flush=True)
                        return total
        except Exception as exc:
            print(f"  fmc connection lost ({type(exc).__name__}); "
                  f"retry {attempt}/{retries}", flush=True)
            time.sleep(min(5 * attempt, 30))

    final = counts()
    print(f"  fmc done: {sum(final.values())} clips {final}", flush=True)
    return sum(final.values())


def fetch_musiccaps(out: Path, n: int) -> int:
    """Pull individual MusicCaps wavs from the Hub (the real class)."""
    from huggingface_hub import HfApi, hf_hub_download

    out.mkdir(parents=True, exist_ok=True)
    api = HfApi()
    files = [s.rfilename for s in api.repo_info(MUSICCAPS_REPO, repo_type="dataset").siblings
             if s.rfilename.endswith(".wav")]
    files.sort()
    print(f"  musiccaps: {len(files)} available, taking {n}", flush=True)

    got = len(list(out.glob("*.wav")))
    for i, name in enumerate(files):
        if got >= n:
            break
        target = out / Path(name).name
        if target.exists() and target.stat().st_size > 4096:
            continue
        try:
            path = hf_hub_download(MUSICCAPS_REPO, name, repo_type="dataset",
                                   local_dir=str(out.parent / "_mc_cache"))
            target.write_bytes(Path(path).read_bytes())
            Path(path).unlink(missing_ok=True)
            got += 1
            if got % 25 == 0:
                print(f"  musiccaps {got}/{n}", flush=True)
        except Exception as exc:
            print(f"  musiccaps skip {name}: {type(exc).__name__}", flush=True)
    print(f"  musiccaps done: {got}", flush=True)
    return got


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", type=Path, required=True)
    ap.add_argument("--per-generator", type=int, default=120)
    ap.add_argument("--real", type=int, default=500)
    ap.add_argument("--skip-fake", action="store_true")
    ap.add_argument("--skip-real", action="store_true")
    args = ap.parse_args()

    if not args.skip_real:
        print("fetching MusicCaps (real class)")
        fetch_musiccaps(args.out / "real", args.real)
    if not args.skip_fake:
        print("streaming FakeMusicCaps (generated class)")
        stream_fakemusiccaps(args.out / "generated", args.per_generator)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
